name: Summarize News for Bharat

on:
  workflow_dispatch: 
  schedule:
    # Triggers daily at 8:30 PM IST (15:00 PM UTC)
    - cron: "0 15 * * *" 

jobs:
  scrape-news-for-bharat:
    runs-on: ubuntu-latest

    env:  
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Summaries News For Bharat
      run: |
        python -m src.bharat

    - name: Commit and Push Generated File
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./summaries/bharat/
        git commit -m "Added summery for Bharat"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Confirm Completion
      run: |
        echo "News summarization completed successfully!"
